jaeger:
  uiIngress:
    enabled: true
    hosts: 
      - jaeger.hades.k8s.dev.spotahome.net
    annotations:
      kubernetes.io/ingress.class: core

exampleApp:
  app:
    resources:
      limits:
        cpu: 20m
        memory: 50Mi
      requests:
        cpu: 5m
        memory: 5Mi
  proxy:
    resources:
      limits:
        cpu: 20m
        memory: 70Mi
      requests:
        cpu: 5m
        memory: 15Mi

apps:
  - name: service-one
    replicaCount: 6
    ingress:
      enabled: true
      hosts: 
        - tracing-example.hades.k8s.dev.spotahome.net
      annotations:
        kubernetes.io/ingress.class: core
  - name: service-two
    replicaCount: 2
    ingress:
      enabled: false
  - name: service-three
    replicaCount: 2
    ingress:
      enabled: false
  - name: service-four
    replicaCount: 2
    ingress:
      enabled: false
  - name: service-five
    replicaCount: 2
    ingress:
      enabled: false
  - name: service-six
    replicaCount: 2
    ingress:
      enabled: false
