{{- $root := . -}}
{{- $appName := printf "%s" "jaeger-all-in-one" -}}

---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ $root.Release.Name }}-{{ $appName }}
  labels:
      release: {{ $root.Release.Name }}
      chart: {{ printf "%s-%s" $root.Chart.Name $root.Chart.Version | quote }}
      heritage: {{ $root.Release.Service | quote }}
      app: {{ $appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
        release: {{ $root.Release.Name }}
        app: {{ $appName }}
  template:
    metadata:
      labels:
        release: {{ $root.Release.Name }}
        app: {{ $appName }}
    spec:
      containers:
        - name: jaeger 
          image: {{ $root.Values.jaeger.allInOneImage }}
          ports:
            - containerPort: 5775
              protocol: UDP
            - containerPort: 6831
              protocol: UDP
            - containerPort: 6832
              protocol: UDP
            - containerPort: 16686
              protocol: TCP
            - containerPort: 9411
              protocol: TCP
          env:
            - name: COLLECTOR_ZIPKIN_HTTP_PORT
              value: "9411"
          readinessProbe:
            httpGet:
              path: "/"
              port: 16686
              initialDelaySeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: {{ $root.Release.Name }}-jaeger-query
  labels:
    release: {{ $root.Release.Name }}
    app: {{ $appName }}
    role: query
spec:
  type: ClusterIP
  ports:
    - name: query-http
      port: 80
      protocol: TCP
      targetPort: 16686
  selector:
    release: {{ $root.Release.Name }}
    app: {{ $appName }}

---
apiVersion: v1
kind: Service
metadata:
  name:  {{ $root.Release.Name }}-jaeger-collector
  labels:
    release: {{ $root.Release.Name }}
    app: {{ $appName }}
    role: collector
spec:
  type: ClusterIP
  ports:
    - name: jaeger-collector-tchannel
      port: 14267
      protocol: TCP
      targetPort: 14267
    - name: jaeger-collector-http
      port: 14268
      protocol: TCP
      targetPort: 14268
    - name: jaeger-collector-zipkin
      port: 9411
      protocol: TCP
      targetPort: 9411
  selector:
    release: {{ $root.Release.Name }}
    app: {{ $appName }}

---

{{- if $root.Values.jaeger.uiIngress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $root.Release.Name }}-jaeger-query
  labels:
    release: {{ $root.Release.Name }}
    app: {{ $appName }}
    role: query
    
  annotations:
    {{- range $key, $value :=  $root.Values.jaeger.uiIngress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    {{- range $host :=  $root.Values.jaeger.uiIngress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $root.Release.Name }}-jaeger-query
              servicePort: 80
    {{- end -}}
  {{- if $root.Values.jaeger.uiIngress.tls }}
  tls:
{{ toYaml $root.Values.jaeger.uiIngress.tls | indent 4 }}
  {{- end -}}
{{- end -}}