

jaeger:
  collectorService: tracing-example-jaeger-collector.svc
  allInOneImage: jaegertracing/all-in-one
  uiIngress:
    enabled: false
    hosts: []
    # Add TLS configuration
    # tls: <TLS_CONFIG>
    # Add custom annotations
    # annotations:
    #   name: value

exampleApp:
  app:
    image: quay.io/slok/tracing-example:latest
    resources:
      limits:
        cpu: 20m
        memory: 20Mi
      requests:
        cpu: 5m
        memory: 5Mi
  proxy:
    image: quay.io/slok/skipper:latest
    resources:
      limits:
        cpu: 20m
        memory: 40Mi
      requests:
        cpu: 5m
        memory: 15Mi
  jaegerAgent:
    image: jaegertracing/jaeger-agent
    resources:
      limits:
        cpu: 20m
        memory: 20Mi
      requests:
        cpu: 5m
        memory: 5Mi

apps:
  - name: service-one
    replicaCount: 1
    ingress:
      enabled: false
      hosts: []
      # Add TLS configuration
      # tls: <TLS_CONFIG>
      # Add custom annotations
      # annotations:
      #   name: value
  - name: service-two
    replicaCount: 2
    ingress:
      enabled: false
      hosts: []
      # Add TLS configuration
      # tls: <TLS_CONFIG>
      # Add custom annotations
      # annotations:
      #   name: value
  - name: service-three
    replicaCount: 1
    ingress:
      enabled: false
      hosts: []
      # Add TLS configuration
      # tls: <TLS_CONFIG>
      # Add custom annotations
      # annotations:
      #   name: value
